server:
  port: 8081

spring:
  application:
    name: subsysa
  mvc:
    view:
      prefix: /view/flt/
      suffix: .flt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/framework?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: kl931106
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  resources:
    static-locations: classpath:/view/ftl

eureka:
  client:
    service-url:
      #defaultZone 这个是不会提示的，此处需要自己写
      #实际上属性应该是service-url,这个属性是个map（key-value）格式；当key是defaultZone的时候才能被解析；所以这里没有提示，
      #但是自己还需要写一个defaultZone；
      defaultZone: http://localhost:5060/eureka/eureka